name: Copies files to remote server

on:
  workflow_call:
    inputs:
      SOURCE_FILES:
        required: true
        type: string
      DEPLOYMENT_DIR:
        required: true
        type: string
    secrets:
      ID_RSA_GITHUB_MALAGACJ:
        required: true
      SERVER_NAME:
        required: true
      SERVER_USER:
        required: true

jobs:
  copy-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create deployment folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ID_RSA_GITHUB_MALAGACJ }}
          script: mkdir -p "${{ env.DEPLOYMENT_DIR }}"

      - name: Copy artifact files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ID_RSA_GITHUB_MALAGACJ }}
          source: "${{ env.SOURCE_FILES }}"
          target: "${{ env.DEPLOYMENT_DIR }}"
